version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile

    volumes:
      - ./server/node_modules:/home/node/app/node_modules
      - ./server:/home/node/app
    environment:
      - PORT=3333
    command: npm run start

  nginx:
    depends_on:
      - app
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "0.0.0.0:80:80"

networks:
  app-network:
    driver: bridge
