version: '1.0.0'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - /home/node/app/node_modules
      - ./server:/home/node/app
    environment:
      - NODE_ENV=PRODUCTION
    networks:
      - app-network
    command: npm run start

  nginx:
    depends_on:
      - app
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
